# Generated by Django 5.2.3 on 2025-06-17 22:12

import django.core.validators
import django.utils.timezone
import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('age', models.PositiveIntegerField(help_text='min. 15-years-old.', validators=[django.core.validators.MinValueValidator(15)])),
                ('username', models.CharField(help_text='Unique username (will be visible by other users)', unique=True, validators=[django.core.validators.MaxLengthValidator(100)])),
                ('first_name', models.CharField(blank=True, max_length=30, validators=[django.core.validators.MaxLengthValidator(30)])),
                ('last_name', models.CharField(blank=True, max_length=30, validators=[django.core.validators.MaxLengthValidator(40)])),
                ('can_be_contacted', models.BooleanField(default=False, help_text='Allow SoftDesk to send you emails to keep you updated about their products')),
                ('can_data_be_shared', models.BooleanField(default=False, help_text='Allow SoftDesk to share your information with third parties in order to customize your experience.')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(blank=True, help_text='Unique email address for the user.', max_length=254, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', user.models.CustomUserManager()),
            ],
        ),
    ]
