# Generated by Django 5.2.3 on 2025-06-20 11:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(help_text='min. 15-years-old.', validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=40, validators=[django.core.validators.MaxLengthValidator(40)]),
        ),
    ]
