# Generated by Django 5.2.3 on 2025-06-16 11:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(help_text='Must be at least 15 years old.', validators=[django.core.validators.MinValueValidator(15)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='can_be_contacted',
            field=models.BooleanField(default=False, help_text='Allow SoftDesk to contact you about your projects.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='can_data_be_shared',
            field=models.BooleanField(default=False, help_text='Allow your data to be shared with third parties.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.MaxLengthValidator(40)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Unique username to display', unique=True, validators=[django.core.validators.MaxLengthValidator(100)]),
        ),
    ]
