# Generated by Django 5.2.3 on 2025-06-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_contributors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_time']},
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('TO_DO', 'to_do'), ('IN_PROGRESS', 'in_progress'), ('FINISHED', 'finished')], default='TODO', max_length=15),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('BACKEND', 'backend'), ('FRONTEND', 'frontend'), ('IOS', 'ios'), ('ANDROID', 'android')], max_length=20),
        ),
    ]
